# Generated by Django 3.0.5 on 2023-10-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_auto_20200508_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentextra',
            name='roll',
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
