# Generated by Django 3.0.5 on 2023-10-10 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20231008_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentextra',
            name='cl',
        ),
        migrations.RemoveField(
            model_name='studentextra',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='studentextra',
            name='status',
        ),
    ]
